Backup/Restore scripts: check if pg_dump/pg_restore commands exist Fixes #1

diff --git a/bin/db_backup b/bin/db_backup
--- a/bin/db_backup
+++ b/bin/db_backup
@@ -95,6 +95,13 @@ shift "$((OPTIND-1))"
 ## BACKUP
 ####
 
+# Check if PG_DUMP exists
+if [ -z "$PG_DUMP" ]; then
+    echo "ERROR: pg_dump command not found"
+    echo "It can likely be installed with the postgresql-client package"
+    echo "Try 'apt-get/yum install postgresql-client'"
+    exit 1
+fi
 
 # Check required parameters
 if [ -z "$DATABASE" ]; then
diff --git a/bin/db_restore b/bin/db_restore
--- a/bin/db_restore
+++ b/bin/db_restore
@@ -81,9 +81,16 @@ shift "$((OPTIND-1))"
 
 
 ####
-## BACKUP
+## RESTORE
 ####
 
+# Check if PG_RESTORE exists
+if [ -z "$PG_RESTORE" ]; then
+    echo "ERROR: pg_restore command not found"
+    echo "It can likely be installed with the postgresql-client package"
+    echo "Try 'apt-get/yum install postgresql-client'"
+    exit 1
+fi
 
 # Check required parameters
 if [ -z "$DATABASE" ]; then
